### ISSUE TITLE
App crush 

### ISSUE THREAD

**Issue by ashomokdev** [ashomokdev/lullabies-v3#1]

**Comment by ashomokdev** [comment]
```
2019-05-13 09:04:32.766 741-741/com.example.android.uamp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.uamp, PID: 741
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.support.v4.media.MediaBrowserCompat$MediaItem.getMediaId()' on a null object reference
        at com.example.android.uamp.ui.MusicPlayerActivity.onMediaItemSelected(MusicPlayerActivity.java:85)
        at com.example.android.uamp.ui.MediaBrowserFragment.lambda$onCreateView$0$MediaBrowserFragment(MediaBrowserFragment.java:177)
        at com.example.android.uamp.ui.-$$Lambda$MediaBrowserFragment$2dWuPHc-s6alm6-q17pCIMYKotg.onItemClick(Unknown Source:2)
        at com.example.android.uamp.tools.ClickableViewPager$TapGestureListener.onSingleTapConfirmed(ClickableViewPager.java:50)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:312)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by ashomokdev** [comment]
Occurs when click to play after returning from task manager (music is playing)
