### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ashomok.lullabies.ui.main_activity.MediaBrowserFragment.onConnected()' on a null object reference

### ISSUE THREAD

**Issue by ashomokdev** [ashomokdev/lullabies-v3#38]
reports here https://play.google.com/apps/publish/?account=7572373447067384777#AndroidMetricsErrorsPlace:p=com.ashomok.lullabies&appid=4974188486488574518&appVersion=PRODUCTION

**Comment by ashomokdev** [comment]
logs added - needs more info

**Comment by ashomokdev** [comment]
Reproduced when use Android back button from About activity

**Comment by ashomokdev** [comment]
Process: com.ashomok.lullabies, PID: 3502
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ashomok.lullabies.ui.main_activity.MediaBrowserFragment.onConnected()' on a null object reference
        at com.ashomok.lullabies.ui.main_activity.MusicPlayerActivity.onMediaControllerConnected(MusicPlayerActivity.java:328)
        at com.ashomok.lullabies.ui.BaseActivity.connectToSession(BaseActivity.java:183)
        at com.ashomok.lullabies.ui.BaseActivity.access$200(BaseActivity.java:40)
        at com.ashomok.lullabies.ui.BaseActivity$2.onConnected(BaseActivity.java:218)
        at android.support.v4.media.MediaBrowserCompat$ConnectionCallback$StubApi21.onConnected(MediaBrowserCompat.java:651)
        at android.support.v4.media.MediaBrowserCompatApi21$ConnectionCallbackProxy.onConnected(MediaBrowserCompatApi21.java:102)
        at android.media.browse.MediaBrowser$6.run(MediaBrowser.java:603)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
